[package]
name = "bvj-6"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16", features = ["mp3"] }
rand = "0.8.5"
rand_chacha = "0.3.1"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
